security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory:
            memory:
                users:
                    testuser:
                        password: '$2y$13$c3df/oQIbossonopF0tf7eC4qLk/JBdmqAMS1kPxSSe1umTYHJQxi'  # Mets ici un hash réel ! vrai mdp : user42
                        roles: ['ROLE_USER']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            # Ajoute ici un bloc d’auth (optionnel pour mémoire simple)
            # http_basic: ~
    access_control:
        - { path: ^/post, roles: ROLE_USER }
        # Ajoute d’autres règles ici si besoin

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
